filtergraph    = sws-flags? filterchain (<semicolon> filterchain)*
sws-flags      = <'sws_flags'> <equals> flags <semicolon>
flags          = #'[^;]+'

filterchain    = !sws-flags filter (<comma> filter)*
filter         = input-linklabels? filter-spec output-linklabels?

input-linklabels  = linklabel+
output-linklabels = linklabel+
linklabel      = <lbracket> name <rbracket>

filter-spec    = filter-name (<equals> filter-arguments)?
filter-name    = name (at name)?

filter-arguments = arg (<colon> arg)*
arg              = key-value | value
key-value        = key <equals> value
key              = #'[^=:,;\s\[\]\'"]+'
<value>          = quoted-string | unquoted-value
unquoted-value   = #'[^=:,;\s\[\]\'"]*'
quoted-string    = <"'">  #"[^']*" <"'">

<name>         = #'[a-zA-Z0-9_:]+'
at           = '@'
equals       = '='
comma        = ','
semicolon    = ';'
lbracket     = '['
rbracket     = ']'
colon        = ':'
