filtergraph = [sws-flags] filterchain (semicolon filterchain)*

sws-flags = <"sws_flags="> flags <semicolon>

filterchain = filter (comma filter)*

filter = [input-labels] filter-spec [output-labels]

input-labels = input-label+
output-labels = output-label+

input-label = <"["> label-name <"]">
output-label = <"["> label-name <"]">

filter-spec = filter-name [<"@"> filter-id] [<"="> filter-arguments]

filter-name = #"[A-Za-z0-9_]+"
filter-id = #"[A-Za-z0-9_]+"
label-name = #"[A-Za-z0-9_]+"

filter-arguments = argument (colon argument)*
argument = key-value | value
key-value = key <"="> value
key = #"[A-Za-z0-9_]+"
value = quoted-value | unquoted-value

quoted-value = <"'"> #"[^']*" <"'">
unquoted-value = #"[^:,;\\[\\]=']*"

flags = #"[^;]*"

comma = <",">
semicolon = <";">
colon = <":">








