program = expression*

<expression> = atom | list | let-binding | for-binding | map | compose | graph-definition | padded-graph

let-binding = <'('> <'let'> binding-vector expression+ <')'>
<binding-vector> = <'['> binding* <']'>
binding = symbol expression

for-binding = <'('> <'for'> <'['> symbol expression <']'> expression+ <')'>

graph-definition = <'('> <'defgraph'> symbol expression* <')'>
padded-graph = <'['> label+ expression* label+ <']'>
compose = <'('> 'compose' expression+ <')'>

list = <'('> expression* <')'>
<mapentry> = keyword expression [<','>]
map = <'{'> mapentry* <'}'>
label = <'['> label-content <']'>
<label-content> = string | number | identifier | for-binding
<atom> = number | boolean | !boolean !number symbol | string | keyword
number = #'-?\d+(\.\d+)?'
string = <'"'> #'[^"]*' <'"'>
<operator> = '=' | '<' | '>' | '<=' | '>=' | '+' | '-' | '*' | '/'
<identifier> = #'[a-zA-Z_][a-zA-Z0-9_\-:]*[?!]?'
symbol = operator | identifier
keyword = <':'> identifier
boolean = "true" | "false"
