name: Build Release - Linux
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  VERSION: 1.1.0

jobs:

  build-appimage:
    name: Appimage build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: graalvm-community

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Cache deps
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}

      - name: Install Meyvn
        run: clojure -Sdeps '{:deps {org.meyvn/meyvn-installer {:mvn/version "1.6.8"}}}' -M -m meyvn-installer.core

      - name: Meyvn run
        run: xvfb-run myvn clean install

      - name: List output
        run: find target -type f

      # - name: Upload output
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: app-image
      #     path: target/imagetool/caonima-${{ env.VERSION }}-x86_64.AppImage
